import { BronzeType } from "../_interfaces/Bronze.interface";

const bronze: BronzeType = {
  vendors: [
    {
      name: "Aeonicus",
      description: "Raid Finder Apparel",
      id: 0,
      items: [
        {
          name: "Regalia of the Burning Scroll",
          cost: 5000,
          id: 0,
          eventOnlyItem: false,
          wowheadId: 215189,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of the Chromatic Hydra",
          cost: 5000,
          id: 1,
          eventOnlyItem: false,
          wowheadId: 215193,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Chronomancer Regalia",
          cost: 5000,
          id: 2,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Guardian Serpent Regalia",
          cost: 5000,
          id: 3,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Exorcist",
          cost: 5000,
          id: 4,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of Ternion Glory",
          cost: 5000,
          id: 5,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Sha Skin Regalia",
          cost: 5000,
          id: 6,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Thousandfold Hells",
          cost: 5000,
          id: 7,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Horned Nightmare",
          cost: 5000,
          id: 8,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Eternal Blossom",
          cost: 5000,
          id: 9,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Haunted Forest",
          cost: 5000,
          id: 10,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Shattered Vale",
          cost: 5000,
          id: 11,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Red Crane",
          cost: 5000,
          id: 12,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Vestments of the Seven Sacred Seals",
          cost: 5000,
          id: 13,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Fire-Charm Vestments",
          cost: 5000,
          id: 14,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Battlegear of the Thousandfold Blades",
          cost: 5000,
          id: 15,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Nine-Tail Battlegear",
          cost: 5000,
          id: 16,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Barbed Assassin Battlegear",
          cost: 5000,
          id: 17,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Yuangol Slayer Battlegear",
          cost: 5000,
          id: 18,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Saurok Stalker",
          cost: 5000,
          id: 19,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Unblinking Vigil",
          cost: 5000,
          id: 20,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of the Firebird",
          cost: 5000,
          id: 21,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of the Witch Doctor",
          cost: 5000,
          id: 22,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of Celestial Harmony",
          cost: 5000,
          id: 23,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Plate of the Lost Catacomb",
          cost: 5000,
          id: 24,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the All-Consuming Maw",
          cost: 5000,
          id: 25,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the Cyclopean Dread",
          cost: 5000,
          id: 26,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "White Tiger Battlegear",
          cost: 5000,
          id: 27,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battlegear of the Lightning Emperor",
          cost: 5000,
          id: 28,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Vestments of Winged Triumph",
          cost: 5000,
          id: 29,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of Resounding Rings",
          cost: 5000,
          id: 30,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Last Mogu",
          cost: 5000,
          id: 31,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Prehistoric Marauder",
          cost: 5000,
          id: 32,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Durus",
      description: "Normal Raid Apparel",
      id: 1,
      items: [
        {
          name: "Regalia of the Burning Scroll",
          cost: 5000,
          id: 33,
          eventOnlyItem: false,
          wowheadId: 215191,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of the Chromatic Hydra",
          cost: 5000,
          id: 34,
          eventOnlyItem: false,
          wowheadId: 215194,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Chronomancer Regalia",
          cost: 5000,
          id: 35,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Guardian Serpent Regalia",
          cost: 5000,
          id: 36,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Exorcist",
          cost: 5000,
          id: 37,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of Ternion Glory",
          cost: 5000,
          id: 38,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Sha Skin Regalia",
          cost: 5000,
          id: 39,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Thousandfold Hells",
          cost: 5000,
          id: 40,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Horned Nightmare",
          cost: 5000,
          id: 41,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Eternal Blossom",
          cost: 5000,
          id: 42,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Haunted Forest",
          cost: 5000,
          id: 43,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Shattered Vale",
          cost: 5000,
          id: 44,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Red Crane",
          cost: 5000,
          id: 45,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Vestments of the Seven Sacred Seals",
          cost: 5000,
          id: 46,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Fire-Charm Vestments",
          cost: 5000,
          id: 47,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Battlegear of the Thousandfold Blades",
          cost: 5000,
          id: 48,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Nine-Tail Battlegear",
          cost: 5000,
          id: 49,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Barbed Assassin Battlegear",
          cost: 5000,
          id: 50,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Yuangol Slayer Battlegear",
          cost: 5000,
          id: 51,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Saurok Stalker",
          cost: 5000,
          id: 52,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Unblinking Vigil",
          cost: 5000,
          id: 53,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of the Firebird",
          cost: 5000,
          id: 54,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of the Witch Doctor",
          cost: 5000,
          id: 55,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of Celestial Harmony",
          cost: 5000,
          id: 56,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Plate of the Lost Catacomb",
          cost: 5000,
          id: 57,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the All-Consuming Maw",
          cost: 5000,
          id: 58,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the Cyclopean Dread",
          cost: 5000,
          id: 59,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "White Tiger Battlegear",
          cost: 5000,
          id: 60,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battlegear of the Lightning Emperor",
          cost: 5000,
          id: 61,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Vestments of Winged Triumph",
          cost: 5000,
          id: 62,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of Resounding Rings 1",
          cost: 5000,
          id: 63,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of Resounding Rings 2",
          cost: 5000,
          id: 64,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Last Mogu",
          cost: 5000,
          id: 65,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Prehistoric Marauder",
          cost: 5000,
          id: 66,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Pythagorus",
      description: "Heroic and Mythic Raid Apparel",
      id: 2,
      items: [
        {
          name: "Regalia of the Burning Scroll",
          cost: 5000,
          id: 67,
          eventOnlyItem: false,
          wowheadId: 215190,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of the Chromatic Hydra",
          cost: 5000,
          id: 68,
          eventOnlyItem: false,
          wowheadId: 215192,
          type: "cloth",
          class: "mage",
        },

        {
          name: "Guardian Serpent Regalia",
          cost: 5000,
          id: 69,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Exorcist",
          cost: 5000,
          id: 70,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Sha Skin Regalia",
          cost: 5000,
          id: 71,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Thousandfold Hells",
          cost: 5000,
          id: 72,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Eternal Blossom",
          cost: 5000,
          id: 73,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Haunted Forest",
          cost: 5000,
          id: 74,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Red Crane",
          cost: 5000,
          id: 75,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Fire-Charm Vestments",
          cost: 5000,
          id: 76,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Battlegear of the Thousandfold Blades",
          cost: 5000,
          id: 77,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Nine-Tail Battlegear",
          cost: 5000,
          id: 78,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Yuangol Slayer Battlegear",
          cost: 5000,
          id: 79,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Saurok Stalker",
          cost: 5000,
          id: 80,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of the Firebird",
          cost: 5000,
          id: 81,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of the Witch Doctor",
          cost: 5000,
          id: 82,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Plate of the Lost Catacomb",
          cost: 5000,
          id: 83,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the All-Consuming Maw",
          cost: 5000,
          id: 84,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "White Tiger Battlegear",
          cost: 5000,
          id: 85,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battlegear of the Lightning Emperor",
          cost: 5000,
          id: 86,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of Resounding Rings",
          cost: 5000,
          id: 87,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Last Mogu",
          cost: 5000,
          id: 88,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Chronomancer Regalia",
          cost: 5000,
          id: 89,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of Ternion Glory",
          cost: 5000,
          id: 90,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Horned Nightmare",
          cost: 5000,
          id: 91,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Shattered Vale",
          cost: 5000,
          id: 92,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Seven Sacred Seals",
          cost: 5000,
          id: 93,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Barbed Assassin Battlegear",
          cost: 5000,
          id: 94,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Battlegear of the Unblinking Vigil",
          cost: 5000,
          id: 95,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of Celestial Harmony",
          cost: 5000,
          id: 96,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Battleplate of the Cyclopean Dread",
          cost: 5000,
          id: 97,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Vestments of Winged Triumph",
          cost: 5000,
          id: 98,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of the Prehistoric Marauder",
          cost: 5000,
          id: 99,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
  ],
};

export default bronze;
