import { BronzeType } from "../_interfaces/Bronze.interface";

const bronze: BronzeType = {
  vendors: [
    {
      name: "Aeonicus",
      description: "Raid Finder Apparel",
      id: 10,
      items: [
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 20000,
          id: 1000,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 20000,
          id: 1001,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 20000,
          id: 1002,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 20000,
          id: 1003,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 20000,
          id: 1004,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 20000,
          id: 1005,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 20000,
          id: 1006,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 20000,
          id: 1007,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements",
          cost: 20000,
          id: 1008,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 20000,
          id: 1009,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 20000,
          id: 1010,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 20000,
          id: 1011,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Funerary Plate of the Chosen Dead",
          cost: 20000,
          id: 1012,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
        },
        {
          name: "Ensemble: Chains of the Chosen Dead",
          cost: 20000,
          id: 1013,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
        },
        {
          name: "Ensemble: Garb of the Chosen Dead",
          cost: 20000,
          id: 1014,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
        },
        {
          name: "Ensemble: Regalia of the Chosen Dead",
          cost: 20000,
          id: 1015,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 20000,
          id: 1016,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 20000,
          id: 1017,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 20000,
          id: 1018,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 20000,
          id: 1019,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 20000,
          id: 1020,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 20000,
          id: 1021,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 20000,
          id: 1022,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 20000,
          id: 1023,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 20000,
          id: 1024,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 20000,
          id: 1025,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 20000,
          id: 1026,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 20000,
          id: 1027,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 20000,
          id: 1028,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 20000,
          id: 1029,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 20000,
          id: 1030,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 20000,
          id: 1031,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 20000,
          id: 1032,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 20000,
          id: 1033,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 20000,
          id: 1034,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 20000,
          id: 1035,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 20000,
          id: 1036,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 20000,
          id: 1037,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 20000,
          id: 1038,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 20000,
          id: 1039,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Durus",
      description: "Normal Raid Apparel",
      id: 11,
      items: [
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 20000,
          id: 1040,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 20000,
          id: 1041,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 20000,
          id: 1042,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 20000,
          id: 1043,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 20000,
          id: 1044,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 20000,
          id: 1045,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 20000,
          id: 1046,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 20000,
          id: 1047,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements",
          cost: 20000,
          id: 1048,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 20000,
          id: 1049,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 20000,
          id: 1050,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 20000,
          id: 1051,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 20000,
          id: 1052,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 20000,
          id: 1053,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 20000,
          id: 1054,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 20000,
          id: 1055,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 20000,
          id: 1056,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 20000,
          id: 1057,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 20000,
          id: 1058,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 20000,
          id: 1059,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 20000,
          id: 1060,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 20000,
          id: 1061,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 20000,
          id: 1062,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 20000,
          id: 1063,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 20000,
          id: 1064,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 20000,
          id: 1065,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 20000,
          id: 1066,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 20000,
          id: 1067,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 20000,
          id: 1068,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 20000,
          id: 1069,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 20000,
          id: 1070,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 20000,
          id: 1071,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 20000,
          id: 1072,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 20000,
          id: 1073,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 20000,
          id: 1074,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 20000,
          id: 1075,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Sacerdormu",
      description: "Heroic Raid Apparel",
      id: 12,
      items: [
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 20000,
          id: 1076,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 20000,
          id: 1077,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 20000,
          id: 1078,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 20000,
          id: 1079,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 20000,
          id: 1080,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 20000,
          id: 1081,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 20000,
          id: 1082,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 20000,
          id: 1083,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements (Ice)",
          cost: 20000,
          id: 1084,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements (Felfire)",
          cost: 20000,
          id: 1085,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 20000,
          id: 1086,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 20000,
          id: 1087,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 20000,
          id: 1088,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 20000,
          id: 1089,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 20000,
          id: 1090,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 20000,
          id: 1091,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 20000,
          id: 1092,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 20000,
          id: 1093,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 20000,
          id: 1094,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 20000,
          id: 1095,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 20000,
          id: 1096,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 20000,
          id: 1097,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 20000,
          id: 1098,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 20000,
          id: 1099,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 20000,
          id: 1100,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 20000,
          id: 1101,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 20000,
          id: 1102,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 20000,
          id: 1103,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 20000,
          id: 1104,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 20000,
          id: 1105,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 20000,
          id: 1106,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 20000,
          id: 1107,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 20000,
          id: 1108,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 20000,
          id: 1109,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 20000,
          id: 1110,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 20000,
          id: 1111,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 20000,
          id: 1112,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Pythagorus",
      description: "Mythic Raid Apparel",
      id: 13,
      items: [
        {
          name: "The First Satyr's Spaulders",
          cost: 30000,
          id: 1113,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Hammer of Vigilance",
          cost: 30000,
          id: 1114,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Scythe of the Unmaker",
          cost: 30000,
          id: 1115,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Taeshalach",
          cost: 30000,
          id: 1116,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 30000,
          id: 1117,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 30000,
          id: 1118,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 30000,
          id: 1119,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 30000,
          id: 1120,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 30000,
          id: 1121,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 30000,
          id: 1122,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 30000,
          id: 1123,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 30000,
          id: 1124,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements",
          cost: 30000,
          id: 1125,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 30000,
          id: 1126,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 30000,
          id: 1127,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 30000,
          id: 1128,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 30000,
          id: 1129,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 30000,
          id: 1130,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 30000,
          id: 1131,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 30000,
          id: 1132,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 30000,
          id: 1133,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 30000,
          id: 1134,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 30000,
          id: 1135,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 30000,
          id: 1136,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 30000,
          id: 1137,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 30000,
          id: 1138,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 30000,
          id: 1139,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 30000,
          id: 1140,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 30000,
          id: 1141,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 30000,
          id: 1142,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 30000,
          id: 1143,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 30000,
          id: 1144,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 30000,
          id: 1145,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 30000,
          id: 1146,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 30000,
          id: 1147,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 30000,
          id: 1148,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 30000,
          id: 1149,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 30000,
          id: 1150,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 30000,
          id: 1151,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 30000,
          id: 1152,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Arturos",
      description: "Dungeon Apparel",
      id: 14,
      items: [
        {
          name: "Ensemble: Seawitch's Terrorcloth",
          cost: 15000,
          id: 1153,
          eventOnlyItem: false,
          wowheadId: 241439,
          type: "cloth",
        },
        {
          name: "Ensemble: Nighthide Coat",
          cost: 15000,
          id: 1154,
          eventOnlyItem: false,
          wowheadId: 241436,
          type: "leather",
        },
        {
          name: "Ensemble: Chains of Nightmare's Embrace",
          cost: 15000,
          id: 1154,
          eventOnlyItem: false,
          wowheadId: 241434,
          type: "mail",
        },
        {
          name: "Ensemble: Suramar Silver Plating",
          cost: 15000,
          id: 1155,
          eventOnlyItem: false,
          wowheadId: 241431,
          type: "plate",
        },
        {
          name: "Ensemble: Vesture of Borrowed Souls",
          cost: 15000,
          id: 1156,
          eventOnlyItem: false,
          wowheadId: 241428,
          type: "cloth",
        },
        {
          name: "Ensemble: Sanguine Oath Vestments",
          cost: 15000,
          id: 1157,
          eventOnlyItem: false,
          wowheadId: 241427,
          type: "cloth",
        },
        {
          name: "Ensemble: Bindings of Hungering Flesh",
          cost: 15000,
          id: 1158,
          eventOnlyItem: false,
          wowheadId: 241425,
          type: "leather",
        },
        {
          name: "Ensemble: Thirsting Hides",
          cost: 15000,
          id: 1159,
          eventOnlyItem: false,
          wowheadId: 241424,
          type: "cloth",
        },
        {
          name: "Ensemble: Armor of the Skyfather's Chosen",
          cost: 15000,
          id: 1160,
          eventOnlyItem: false,
          wowheadId: 241422,
          type: "mail",
        },
        {
          name: "Ensemble: Ravensteel Mail",
          cost: 15000,
          id: 1161,
          eventOnlyItem: false,
          wowheadId: 241421,
          type: "mail",
        },
        {
          name: "Ensemble: Honorforged Valorplate",
          cost: 15000,
          id: 1162,
          eventOnlyItem: false,
          wowheadId: 241419,
          type: "plate",
        },
        {
          name: "Ensemble: Bloodforged Battleplate",
          cost: 15000,
          id: 1163,
          eventOnlyItem: false,
          wowheadId: 241418,
          type: "plate",
        },
        {
          name: "Ensemble: Nightforged Felplate",
          cost: 15000,
          id: 1164,
          eventOnlyItem: false,
          wowheadId: 241417,
          type: "plate",
        },
        {
          name: "Ensemble: Raiment of Night Eternal",
          cost: 15000,
          id: 1165,
          eventOnlyItem: false,
          wowheadId: 241426,
          type: "cloth",
        },
        {
          name: "Ensemble: Guise of the Nightstalker",
          cost: 15000,
          id: 1166,
          eventOnlyItem: false,
          wowheadId: 241423,
          type: "leather",
        },
        {
          name: "Ensemble: Scalemail of Devouring Night",
          cost: 15000,
          id: 1167,
          eventOnlyItem: false,
          wowheadId: 241420,
          type: "mail",
        },
      ],
    },
    {
      name: "Jakkus",
      description: "Class Mounts",
      id: 15,
      items: [
        {
          name: "Reins of the Highlord's Felscorned Charger",
          cost: 20000,
          id: 1168,
          eventOnlyItem: true,
          wowheadId: 253028,
          class: "paladin",
        },
        {
          name: "Iron Reins of the Felscorned War Wyrm",
          cost: 20000,
          id: 1169,
          eventOnlyItem: true,
          wowheadId: 253033,
          class: "warrior",
        },
        {
          name: "Felscorned Reins of the Vilebrood Vanquisher",
          cost: 20000,
          id: 1170,
          eventOnlyItem: true,
          wowheadId: 252954,
          class: "death knight",
        },
        {
          name: "Reins of the Felscorned Wolfhawk",
          cost: 20000,
          id: 1171,
          eventOnlyItem: true,
          wowheadId: 253025,
          class: "hunter",
        },
        {
          name: "Felscorned Tempest Totem",
          cost: 20000,
          id: 1172,
          eventOnlyItem: true,
          wowheadId: 253031,
          class: "shaman",
        },
        {
          name: "Shadowblade's Reins of Felscorned Portent",
          cost: 20000,
          id: 1173,
          eventOnlyItem: true,
          wowheadId: 253030,
          class: "rogue",
        },
        {
          name: "Felscorned Grandmaster's Bell",
          cost: 20000,
          id: 1174,
          eventOnlyItem: true,
          wowheadId: 253027,
          class: "monk",
        },
        {
          name: "Feldruid's Scornwing Idol",
          cost: 20000,
          id: 1175,
          eventOnlyItem: true,
          wowheadId: 253024,
          class: "druid",
        },
        {
          name: "Slayer's Reins of the Felscorned Shrieker",
          cost: 20000,
          id: 1176,
          eventOnlyItem: true,
          wowheadId: 253013,
          class: "demon hunter",
        },
        {
          name: "Felscorned Seeker's Whistle",
          cost: 20000,
          id: 1177,
          eventOnlyItem: true,
          wowheadId: 253029,
          class: "priest",
        },
        {
          name: "Felscorned Reins of the Netherlord's Dreadsteed",
          cost: 20000,
          id: 1178,
          eventOnlyItem: true,
          wowheadId: 253032,
          class: "warlock",
        },
        {
          name: "Archmage's Felscorned Disc",
          cost: 20000,
          id: 1179,
          eventOnlyItem: true,
          wowheadId: 253026,
          class: "mage",
        },
      ],
    },
    {
      name: "Larah",
      description: "World Apparel",
      id: 5,
      items: [
        {
          name: "Spirit-Waker's Vestments (Blue)",
          cost: 750,
          id: 139,
          eventOnlyItem: false,
          wowheadId: 215183,
          type: "cloth",
        },
        {
          name: "Spirit-Waker's Vestments (Green)",
          cost: 750,
          id: 140,
          eventOnlyItem: false,
          wowheadId: 215184,
          type: "cloth",
        },
        {
          name: "Spirit-Waker's Vestments (Red)",
          cost: 750,
          id: 141,
          eventOnlyItem: false,
          wowheadId: 215185,
          type: "cloth",
        },
        {
          name: "Mistwalker's Vestments (Blue)",
          cost: 750,
          id: 142,
          eventOnlyItem: false,
          wowheadId: 215186,
          type: "cloth",
        },
        {
          name: "Mistwalker's Vestments (Original)",
          cost: 750,
          id: 143,
          eventOnlyItem: false,
          wowheadId: 215187,
          type: "cloth",
        },
        {
          name: "Mistwalker's Vestments (White)",
          cost: 750,
          id: 144,
          eventOnlyItem: false,
          wowheadId: 215188,
          type: "cloth",
        },
        {
          name: "Vestments of the Eternal Dynasty (Black)",
          cost: 2000,
          id: 145,
          eventOnlyItem: false,
          wowheadId: 215216,
          type: "cloth",
        },
        {
          name: "Vestments of the Eternal Dynasty (Blue)",
          cost: 2000,
          id: 146,
          eventOnlyItem: false,
          wowheadId: 215217,
          type: "cloth",
        },
        {
          name: "Vestments of the Eternal Dynasty (Yellow)",
          cost: 2000,
          id: 147,
          eventOnlyItem: false,
          wowheadId: 215218,
          type: "cloth",
        },
        {
          name: "Thunderpaw Battlegear (Dark)",
          cost: 750,
          id: 148,
          eventOnlyItem: false,
          wowheadId: 215225,
          type: "leather",
        },
        {
          name: "Thunderpaw Battlegear (Light)",
          cost: 750,
          id: 149,
          eventOnlyItem: false,
          wowheadId: 215226,
          type: "leather",
        },
        {
          name: "Thunderpaw Battlegear (Original)",
          cost: 750,
          id: 150,
          eventOnlyItem: false,
          wowheadId: 215227,
          type: "leather",
        },
        {
          name: "Thunderpaw Battlegear (Red)",
          cost: 750,
          id: 151,
          eventOnlyItem: false,
          wowheadId: 215228,
          type: "leather",
        },
        {
          name: "Mistveil Leathers (Black)",
          cost: 750,
          id: 152,
          eventOnlyItem: false,
          wowheadId: 215229,
          type: "leather",
        },
        {
          name: "Mistveil Leathers (Brown)",
          cost: 750,
          id: 153,
          eventOnlyItem: false,
          wowheadId: 215230,
          type: "leather",
        },
        {
          name: "Mistveil Leathers (Crimson)",
          cost: 750,
          id: 154,
          eventOnlyItem: false,
          wowheadId: 215231,
          type: "leather",
        },
        {
          name: "Mistveil Leathers (Indigo)",
          cost: 750,
          id: 155,
          eventOnlyItem: false,
          wowheadId: 215232,
          type: "leather",
        },
        {
          name: "Snowdrift Battlegear (Blue)",
          cost: 2000,
          id: 156,
          eventOnlyItem: false,
          wowheadId: 215269,
          type: "leather",
        },
        {
          name: "Snowdrift Battlegear (Brown)",
          cost: 2000,
          id: 157,
          eventOnlyItem: false,
          wowheadId: 215270,
          type: "leather",
        },
        {
          name: "Snowdrift Battlegear (Red)",
          cost: 2000,
          id: 158,
          eventOnlyItem: false,
          wowheadId: 215271,
          type: "leather",
        },
        {
          name: "Trailseeker's Laminar Armor (Black)",
          cost: 750,
          id: 159,
          eventOnlyItem: false,
          wowheadId: 215278,
          type: "mail",
        },
        {
          name: "Trailseeker's Laminar Armor (Gold)",
          cost: 750,
          id: 160,
          eventOnlyItem: false,
          wowheadId: 215279,
          type: "mail",
        },
        {
          name: "Trailseeker's Laminar Armor (Green)",
          cost: 750,
          id: 161,
          eventOnlyItem: false,
          wowheadId: 215280,
          type: "mail",
        },
        {
          name: "Trailseeker's Laminar Armor (White)",
          cost: 750,
          id: 162,
          eventOnlyItem: false,
          wowheadId: 215281,
          type: "mail",
        },
        {
          name: "Dawnwatcher's Scale Armor (Blue)",
          cost: 750,
          id: 163,
          eventOnlyItem: false,
          wowheadId: 215282,
          type: "mail",
        },
        {
          name: "Dawnwatcher's Scale Armor (Purple)",
          cost: 750,
          id: 164,
          eventOnlyItem: false,
          wowheadId: 215283,
          type: "mail",
        },
        {
          name: "Dawnwatcher's Scale Armor (Red)",
          cost: 750,
          id: 165,
          eventOnlyItem: false,
          wowheadId: 215284,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia (Blue)",
          cost: 2000,
          id: 166,
          eventOnlyItem: false,
          wowheadId: 215306,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia (Brown)",
          cost: 2000,
          id: 167,
          eventOnlyItem: false,
          wowheadId: 215307,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia (Red)",
          cost: 2000,
          id: 168,
          eventOnlyItem: false,
          wowheadId: 215308,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia (Yellow)",
          cost: 2000,
          id: 169,
          eventOnlyItem: false,
          wowheadId: 215309,
          type: "mail",
        },
        {
          name: "Spiritguard's Warplate (Blue)",
          cost: 750,
          id: 170,
          eventOnlyItem: false,
          wowheadId: 215313,
          type: "plate",
        },
        {
          name: "Spiritguard's Warplate (Gold)",
          cost: 750,
          id: 171,
          eventOnlyItem: false,
          wowheadId: 215314,
          type: "plate",
        },
        {
          name: "Spiritguard's Warplate (Silver)",
          cost: 750,
          id: 172,
          eventOnlyItem: false,
          wowheadId: 215315,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate (Green)",
          cost: 750,
          id: 173,
          eventOnlyItem: false,
          wowheadId: 215316,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate (Purple)",
          cost: 750,
          id: 174,
          eventOnlyItem: false,
          wowheadId: 215317,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate (Red)",
          cost: 750,
          id: 175,
          eventOnlyItem: false,
          wowheadId: 215318,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate (Yellow)",
          cost: 750,
          id: 176,
          eventOnlyItem: false,
          wowheadId: 215319,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate (Black)",
          cost: 2000,
          id: 177,
          eventOnlyItem: false,
          wowheadId: 215348,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate (Blue)",
          cost: 2000,
          id: 178,
          eventOnlyItem: false,
          wowheadId: 215349,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate (Green)",
          cost: 2000,
          id: 179,
          eventOnlyItem: false,
          wowheadId: 215350,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate (Red)",
          cost: 2000,
          id: 180,
          eventOnlyItem: false,
          wowheadId: 215351,
          type: "plate",
        },
        {
          name: "Guise of the Shado-Pan",
          cost: 2500,
          id: 181,
          eventOnlyItem: true,
          wowheadId: 215219,
        },
        {
          name: "Guise of the Shado-Pan",
          cost: 2500,
          id: 182,
          eventOnlyItem: true,
          wowheadId: 215220,
        },
        {
          name: "Tian Monastery Clothing",
          cost: 1250,
          id: 183,
          eventOnlyItem: true,
          wowheadId: 215238,
        },
        {
          name: "Tian Monastery Clothing",
          cost: 1250,
          id: 184,
          eventOnlyItem: true,
          wowheadId: 215239,
        },
        {
          name: "Tian Monastery Clothing",
          cost: 1250,
          id: 185,
          eventOnlyItem: true,
          wowheadId: 215240,
        },
        {
          name: "Kor'kron Shaman Vestments",
          cost: 2500,
          id: 186,
          eventOnlyItem: true,
          wowheadId: 215275,
        },
        {
          name: "Kor'kron Shaman Vestments",
          cost: 2500,
          id: 187,
          eventOnlyItem: true,
          wowheadId: 215276,
        },
        {
          name: "Kor'kron Shaman Vestments",
          cost: 2500,
          id: 188,
          eventOnlyItem: true,
          wowheadId: 215277,
        },
        {
          name: "Sun Pearl Clothing",
          cost: 1250,
          id: 189,
          eventOnlyItem: true,
          wowheadId: 215285,
        },
        {
          name: "Sun Pearl Clothing",
          cost: 1250,
          id: 190,
          eventOnlyItem: true,
          wowheadId: 215286,
        },
        {
          name: "Sun Pearl Clothing",
          cost: 1250,
          id: 191,
          eventOnlyItem: true,
          wowheadId: 215287,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 192,
          eventOnlyItem: true,
          wowheadId: 215352,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 193,
          eventOnlyItem: true,
          wowheadId: 215353,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 194,
          eventOnlyItem: true,
          wowheadId: 215354,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 195,
          eventOnlyItem: true,
          wowheadId: 215355,
        },
        {
          name: "Vestments of Serenity",
          cost: 1250,
          id: 196,
          eventOnlyItem: true,
          wowheadId: 215356,
        },
        {
          name: "Vestments of Serenity",
          cost: 1250,
          id: 197,
          eventOnlyItem: true,
          wowheadId: 215357,
        },
        {
          name: "Vestments of Serenity",
          cost: 1250,
          id: 198,
          eventOnlyItem: true,
          wowheadId: 215358,
        },
      ],
    },
    {
      name: "Hemet XVII",
      description: "Beastmaster",
      id: 6,
      items: [
        {
          name: "Sky Surfer",
          cost: 2200,
          id: 200,
          eventOnlyItem: true,
          wowheadId: 213582,
        },
        {
          name: "Golden Discus",
          cost: 2200,
          id: 199,
          eventOnlyItem: true,
          wowheadId: 213576,
        },
        {
          name: "Mogu Hazeblazer",
          cost: 2200,
          id: 201,
          eventOnlyItem: true,
          wowheadId: 213584,
        },
        {
          name: "Feathered Windsurfer",
          cost: 2200,
          id: 202,
          eventOnlyItem: true,
          wowheadId: 213595,
        },
        {
          name: "Jungle Riding Crane",
          cost: 2200,
          id: 270,
          eventOnlyItem: true,
          wowheadId: 0,
        },
        {
          name: "Gilded Riding Crane",
          cost: 2200,
          id: 208,
          eventOnlyItem: true,
          wowheadId: 213602,
        },
        {
          name: "Pale Riding Crane",
          cost: 2200,
          id: 209,
          eventOnlyItem: true,
          wowheadId: 213603,
        },
        {
          name: "Rose Riding Crane",
          cost: 2200,
          id: 211,
          eventOnlyItem: true,
          wowheadId: 213605,
        },
        {
          name: "Silver Riding Crane",
          cost: 2200,
          id: 212,
          eventOnlyItem: true,
          wowheadId: 213606,
        },
        {
          name: "Luxurious Riding Crane",
          cost: 2200,
          id: 213,
          eventOnlyItem: true,
          wowheadId: 213607,
        },
        {
          name: "Tropical Riding Crane",
          cost: 2200,
          id: 210,
          eventOnlyItem: true,
          wowheadId: 213604,
        },
        {
          name: "Snowy Riding Goat",
          cost: 2200,
          id: 214,
          eventOnlyItem: true,
          wowheadId: 213608,
        },
        {
          name: "Little Red Riding Goat",
          cost: 2200,
          id: 215,
          eventOnlyItem: true,
          wowheadId: 213609,
        },
        {
          name: "Riverwalker Mushan",
          cost: 2200,
          id: 223,
          eventOnlyItem: true,
          wowheadId: 213628,
        },
        {
          name: "Palehide Mushan Beast",
          cost: 2200,
          id: 222,
          eventOnlyItem: true,
          wowheadId: 213627,
        },
        {
          name: "Black Riding Yak",
          cost: 2200,
          id: 271,
          eventOnlyItem: true,
          wowheadId: 0,
        },
        {
          name: "Modest Expedition Yak",
          cost: 2200,
          id: 272,
          eventOnlyItem: true,
          wowheadId: 0,
        },
        {
          name: "Kafa Yak",
          cost: 2200,
          id: 273,
          eventOnlyItem: true,
          wowheadId: 0,
        },
        {
          name: "Purple Shado-Pan Riding Tiger",
          cost: 4400,
          id: 221,
          eventOnlyItem: true,
          wowheadId: 213626,
        },
        {
          name: "Cobalt Juggernaut",
          cost: 4400,
          id: 219,
          eventOnlyItem: true,
          wowheadId: 213624,
        },
        {
          name: "Fel Iron Juggernaut",
          cost: 4400,
          id: 220,
          eventOnlyItem: true,
          wowheadId: 213625,
        },
        {
          name: "Bloody Skyscreamer",
          cost: 4400,
          id: 218,
          eventOnlyItem: true,
          wowheadId: 213623,
        },
        {
          name: "Night Pterrorwing",
          cost: 4400,
          id: 217,
          eventOnlyItem: true,
          wowheadId: 213622,
        },
        {
          name: "Jade Pterrordax",
          cost: 4400,
          id: 216,
          eventOnlyItem: true,
          wowheadId: 213621,
        },
        {
          name: "Amber Pterrordax",
          cost: 4400,
          id: 224,
          eventOnlyItem: true,
          wowheadId: 218111,
        },
        {
          name: "Marble Quilen",
          cost: 6600,
          id: 206,
          eventOnlyItem: true,
          wowheadId: 213600,
        },
        {
          name: "Guardian Quilen",
          cost: 6600,
          id: 207,
          eventOnlyItem: true,
          wowheadId: 213601,
        },
        {
          name: "Dashing Windsteed",
          cost: 6600,
          id: 205,
          eventOnlyItem: true,
          wowheadId: 213598,
        },
        {
          name: "Forest Windsteed",
          cost: 6600,
          id: 204,
          eventOnlyItem: true,
          wowheadId: 213597,
        },
        {
          name: "Daystorm Windsteed",
          cost: 6600,
          id: 203,
          eventOnlyItem: true,
          wowheadId: 213596,
        },
        {
          name: "Amber Primordial Direhorn",
          cost: 18700,
          id: 274,
          eventOnlyItem: false,
          wowheadId: 94230,
        },
        {
          name: "Jade Primordial Direhorn",
          cost: 18700,
          id: 275,
          eventOnlyItem: false,
          wowheadId: 94231,
        },
        {
          name: "Slate Primordial Direhorn",
          cost: 18700,
          id: 231,
          eventOnlyItem: false,
          wowheadId: 94229,
        },
        {
          name: "Cobalt Primordial Direhorn",
          cost: 38500,
          id: 230,
          eventOnlyItem: false,
          wowheadId: 94228,
        },
        {
          name: "Son of Galleon",
          cost: 38500,
          id: 227,
          eventOnlyItem: false,
          wowheadId: 89783,
        },
        {
          name: "Spawn of Horridon",
          cost: 38500,
          id: 229,
          eventOnlyItem: false,
          wowheadId: 93666,
        },
        {
          name: "Clutch of Ji-Kun",
          cost: 38500,
          id: 233,
          eventOnlyItem: false,
          wowheadId: 95059,
        },
        {
          name: "Astral Cloud Serpent",
          cost: 18700,
          id: 226,
          eventOnlyItem: false,
          wowheadId: 87777,
        },
        {
          name: "Thundering Onyx Cloud Serpent",
          cost: 38500,
          id: 235,
          eventOnlyItem: false,
          wowheadId: 104269,
        },
        {
          name: "Heavenly Onyx Cloud Serpent",
          cost: 38500,
          id: 225,
          eventOnlyItem: false,
          wowheadId: 87771,
        },
        {
          name: "Thundering Cobalt Cloud Serpent",
          cost: 38500,
          id: 232,
          eventOnlyItem: false,
          wowheadId: 95057,
        },
        {
          name: "Thundering Ruby Cloud Serpent",
          cost: 38500,
          id: 228,
          eventOnlyItem: false,
          wowheadId: 90655,
        },
        {
          name: "Kor'kron Juggernaut",
          cost: 38500,
          id: 234,
          eventOnlyItem: false,
          wowheadId: 104253,
        },
      ],
    },
    {
      name: "Horos",
      description: "Rare Collections",
      id: 7,
      items: [
        {
          name: "Mini Mana Bomb",
          cost: 500,
          id: 257,
          eventOnlyItem: true,
          wowheadId: 89205,
        },
        {
          name: "Theramore Tabard",
          cost: 500,
          id: 276,
          eventOnlyItem: true,
          wowheadId: 89196,
        },
        {
          name: "Odd Polished Stone",
          cost: 2200,
          id: 236,
          eventOnlyItem: false,
          wowheadId: 104262,
        },
        {
          name: "Battle Horn",
          cost: 3850,
          id: 237,
          eventOnlyItem: false,
          wowheadId: 86565,
        },
        {
          name: "Bottled Tornado",
          cost: 3850,
          id: 238,
          eventOnlyItem: false,
          wowheadId: 134023,
        },
        {
          name: "Chalice of Secrets",
          cost: 3850,
          id: 239,
          eventOnlyItem: false,
          wowheadId: 86575,
        },
        {
          name: "Essence of the Breeze",
          cost: 3850,
          id: 240,
          eventOnlyItem: false,
          wowheadId: 86590,
        },
        {
          name: "Helpful Wikky's Whistle",
          cost: 3850,
          id: 241,
          eventOnlyItem: false,
          wowheadId: 86594,
        },
        {
          name: "Kang's Bindstone",
          cost: 3850,
          id: 242,
          eventOnlyItem: false,
          wowheadId: 86571,
        },
        {
          name: "Ai-Li's Skymirror",
          cost: 4950,
          id: 243,
          eventOnlyItem: false,
          wowheadId: 86589,
        },
        {
          name: "Eternal Warrior's Sigil",
          cost: 4950,
          id: 244,
          eventOnlyItem: false,
          wowheadId: 86578,
        },
        {
          name: "Farwater Conch",
          cost: 4950,
          id: 245,
          eventOnlyItem: false,
          wowheadId: 86581,
        },
        {
          name: "Hozen Beach Ball",
          cost: 4950,
          id: 246,
          eventOnlyItem: false,
          wowheadId: 86593,
        },
        {
          name: "Panflute of Pandaria",
          cost: 4950,
          id: 247,
          eventOnlyItem: false,
          wowheadId: 86586,
        },
        {
          name: "Salyin Battle Banner",
          cost: 4950,
          id: 248,
          eventOnlyItem: false,
          wowheadId: 86583,
        },
        {
          name: "Shard of Archstone",
          cost: 4950,
          id: 249,
          eventOnlyItem: false,
          wowheadId: 86573,
        },
        {
          name: "Aqua Jewel",
          cost: 7700,
          id: 250,
          eventOnlyItem: false,
          wowheadId: 86582,
        },
        {
          name: "Mr. Smite's Brass Compass",
          cost: 7700,
          id: 251,
          eventOnlyItem: false,
          wowheadId: 86568,
        },
        {
          name: "Pandaren Firework Launcher",
          cost: 7700,
          id: 252,
          eventOnlyItem: false,
          wowheadId: 86588,
        },
        {
          name: "Blackflame Daggers",
          cost: 38500,
          id: 253,
          eventOnlyItem: false,
          wowheadId: 104302,
        },
        {
          name: "Warning Sign",
          cost: 38500,
          id: 254,
          eventOnlyItem: false,
          wowheadId: 104331,
        },
        {
          name: "Gastropod Shell",
          cost: 50000,
          id: 255,
          eventOnlyItem: false,
          wowheadId: 98136,
        },
        {
          name: "Eternal Kiln",
          cost: 50000,
          id: 256,
          eventOnlyItem: false,
          wowheadId: 104309,
        },
      ],
    },
  ],
};

export default bronze;
