import { BronzeType } from "../_interfaces/Bronze.interface";

const bronze: BronzeType = {
  vendors: [
    {
      name: "Aeonicus",
      description: "Raid Finder Apparel",
      id: 0,
      items: [
        {
          name: "Regalia of the Burning Scroll",
          cost: 5000,
          id: 0,
          eventOnlyItem: false,
          wowheadId: 215189,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of the Chromatic Hydra",
          cost: 5000,
          id: 1,
          eventOnlyItem: false,
          wowheadId: 215193,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Chronomancer Regalia",
          cost: 5000,
          id: 2,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Guardian Serpent Regalia",
          cost: 5000,
          id: 3,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Exorcist",
          cost: 5000,
          id: 4,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of Ternion Glory",
          cost: 5000,
          id: 5,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Sha Skin Regalia",
          cost: 5000,
          id: 6,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Thousandfold Hells",
          cost: 5000,
          id: 7,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Horned Nightmare",
          cost: 5000,
          id: 8,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Eternal Blossom",
          cost: 5000,
          id: 9,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Haunted Forest",
          cost: 5000,
          id: 10,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Shattered Vale",
          cost: 5000,
          id: 11,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Red Crane",
          cost: 5000,
          id: 12,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Vestments of the Seven Sacred Seals",
          cost: 5000,
          id: 13,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Fire-Charm Vestments",
          cost: 5000,
          id: 14,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Battlegear of the Thousandfold Blades",
          cost: 5000,
          id: 15,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Nine-Tail Battlegear",
          cost: 5000,
          id: 16,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Barbed Assassin Battlegear",
          cost: 5000,
          id: 17,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Yuangol Slayer Battlegear",
          cost: 5000,
          id: 18,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Saurok Stalker",
          cost: 5000,
          id: 19,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Unblinking Vigil",
          cost: 5000,
          id: 20,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of the Firebird",
          cost: 5000,
          id: 21,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of the Witch Doctor",
          cost: 5000,
          id: 22,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of Celestial Harmony",
          cost: 5000,
          id: 23,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Plate of the Lost Catacomb",
          cost: 5000,
          id: 24,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the All-Consuming Maw",
          cost: 5000,
          id: 25,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the Cyclopean Dread",
          cost: 5000,
          id: 26,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "White Tiger Battlegear",
          cost: 5000,
          id: 27,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battlegear of the Lightning Emperor",
          cost: 5000,
          id: 28,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Vestments of Winged Triumph",
          cost: 5000,
          id: 29,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of Resounding Rings",
          cost: 5000,
          id: 30,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Last Mogu",
          cost: 5000,
          id: 31,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Prehistoric Marauder",
          cost: 5000,
          id: 32,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Durus",
      description: "Normal Raid Apparel",
      id: 1,
      items: [
        {
          name: "Regalia of the Burning Scroll",
          cost: 5000,
          id: 33,
          eventOnlyItem: false,
          wowheadId: 215191,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of the Chromatic Hydra",
          cost: 5000,
          id: 34,
          eventOnlyItem: false,
          wowheadId: 215194,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Chronomancer Regalia",
          cost: 5000,
          id: 35,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Guardian Serpent Regalia",
          cost: 5000,
          id: 36,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Exorcist",
          cost: 5000,
          id: 37,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of Ternion Glory",
          cost: 5000,
          id: 38,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Sha Skin Regalia",
          cost: 5000,
          id: 39,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Thousandfold Hells",
          cost: 5000,
          id: 40,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Horned Nightmare",
          cost: 5000,
          id: 41,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Eternal Blossom",
          cost: 5000,
          id: 42,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Haunted Forest",
          cost: 5000,
          id: 43,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Shattered Vale",
          cost: 5000,
          id: 44,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Red Crane",
          cost: 5000,
          id: 45,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Vestments of the Seven Sacred Seals",
          cost: 5000,
          id: 46,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Fire-Charm Vestments",
          cost: 5000,
          id: 47,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Battlegear of the Thousandfold Blades",
          cost: 5000,
          id: 48,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Nine-Tail Battlegear",
          cost: 5000,
          id: 49,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Barbed Assassin Battlegear",
          cost: 5000,
          id: 50,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Yuangol Slayer Battlegear",
          cost: 5000,
          id: 51,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Saurok Stalker",
          cost: 5000,
          id: 52,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Unblinking Vigil",
          cost: 5000,
          id: 53,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of the Firebird",
          cost: 5000,
          id: 54,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of the Witch Doctor",
          cost: 5000,
          id: 55,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of Celestial Harmony",
          cost: 5000,
          id: 56,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Plate of the Lost Catacomb",
          cost: 5000,
          id: 57,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the All-Consuming Maw",
          cost: 5000,
          id: 58,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the Cyclopean Dread",
          cost: 5000,
          id: 59,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "White Tiger Battlegear",
          cost: 5000,
          id: 60,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battlegear of the Lightning Emperor",
          cost: 5000,
          id: 61,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Vestments of Winged Triumph",
          cost: 5000,
          id: 62,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of Resounding Rings 1",
          cost: 5000,
          id: 63,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of Resounding Rings 2",
          cost: 5000,
          id: 64,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Last Mogu",
          cost: 5000,
          id: 65,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Prehistoric Marauder",
          cost: 5000,
          id: 66,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Pythagorus",
      description: "Heroic and Mythic Raid Apparel",
      id: 2,
      items: [
        {
          name: "Regalia of the Burning Scroll",
          cost: 5000,
          id: 67,
          eventOnlyItem: false,
          wowheadId: 215190,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of the Chromatic Hydra",
          cost: 5000,
          id: 68,
          eventOnlyItem: false,
          wowheadId: 215192,
          type: "cloth",
          class: "mage",
        },

        {
          name: "Guardian Serpent Regalia",
          cost: 5000,
          id: 69,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Exorcist",
          cost: 5000,
          id: 70,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Sha Skin Regalia",
          cost: 5000,
          id: 71,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Regalia of the Thousandfold Hells",
          cost: 5000,
          id: 72,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Eternal Blossom",
          cost: 5000,
          id: 73,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Haunted Forest",
          cost: 5000,
          id: 74,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Red Crane",
          cost: 5000,
          id: 75,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Fire-Charm Vestments",
          cost: 5000,
          id: 76,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Battlegear of the Thousandfold Blades",
          cost: 5000,
          id: 77,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Nine-Tail Battlegear",
          cost: 5000,
          id: 78,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Yuangol Slayer Battlegear",
          cost: 5000,
          id: 79,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Battlegear of the Saurok Stalker",
          cost: 5000,
          id: 80,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of the Firebird",
          cost: 5000,
          id: 81,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Regalia of the Witch Doctor",
          cost: 5000,
          id: 82,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Plate of the Lost Catacomb",
          cost: 5000,
          id: 83,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Battleplate of the All-Consuming Maw",
          cost: 5000,
          id: 84,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "White Tiger Battlegear",
          cost: 5000,
          id: 85,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battlegear of the Lightning Emperor",
          cost: 5000,
          id: 86,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of Resounding Rings",
          cost: 5000,
          id: 87,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Battleplate of the Last Mogu",
          cost: 5000,
          id: 88,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Chronomancer Regalia",
          cost: 5000,
          id: 89,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Regalia of Ternion Glory",
          cost: 5000,
          id: 90,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Regalia of the Horned Nightmare",
          cost: 5000,
          id: 91,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Vestments of the Shattered Vale",
          cost: 5000,
          id: 92,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Vestments of the Seven Sacred Seals",
          cost: 5000,
          id: 93,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Barbed Assassin Battlegear",
          cost: 5000,
          id: 94,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Battlegear of the Unblinking Vigil",
          cost: 5000,
          id: 95,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Regalia of Celestial Harmony",
          cost: 5000,
          id: 96,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Battleplate of the Cyclopean Dread",
          cost: 5000,
          id: 97,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Vestments of Winged Triumph",
          cost: 5000,
          id: 98,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Battleplate of the Prehistoric Marauder",
          cost: 5000,
          id: 99,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Arturos",
      description: "Dungeon Apparel",
      id: 3,
      items: [
        {
          name: "Breezebinder's Vestments",
          cost: 2500,
          id: 100,
          eventOnlyItem: false,
          wowheadId: 215176,
          type: "cloth",
        },
        {
          name: "Breezebinder's Vestments",
          cost: 2500,
          id: 101,
          eventOnlyItem: false,
          wowheadId: 215181,
          type: "cloth",
        },
        {
          name: "Breezebinder's Vestments",
          cost: 2500,
          id: 102,
          eventOnlyItem: false,
          wowheadId: 215182,
          type: "cloth",
        },
        {
          name: "Mogubreaker Battlegear",
          cost: 2500,
          id: 103,
          eventOnlyItem: false,
          wowheadId: 215221,
          type: "leather",
        },
        {
          name: "Mogubreaker Battlegear",
          cost: 2500,
          id: 104,
          eventOnlyItem: false,
          wowheadId: 215222,
          type: "leather",
        },
        {
          name: "Mogubreaker Battlegear",
          cost: 2500,
          id: 105,
          eventOnlyItem: false,
          wowheadId: 215223,
          type: "leather",
        },
        {
          name: "Mogubreaker Battlegear",
          cost: 2500,
          id: 106,
          eventOnlyItem: false,
          wowheadId: 215224,
          type: "leather",
        },
        {
          name: "Mogu Lord's Regalia",
          cost: 2500,
          id: 107,
          eventOnlyItem: false,
          wowheadId: 215272,
          type: "mail",
        },
        {
          name: "Mogu Lord's Regalia",
          cost: 2500,
          id: 108,
          eventOnlyItem: false,
          wowheadId: 215273,
          type: "mail",
        },
        {
          name: "Mogu Lord's Regalia",
          cost: 2500,
          id: 109,
          eventOnlyItem: false,
          wowheadId: 215274,
          type: "mail",
        },
        {
          name: "Swarmbreaker's Battleplate",
          cost: 2500,
          id: 110,
          eventOnlyItem: false,
          wowheadId: 215310,
          type: "plate",
        },
        {
          name: "Swarmbreaker's Battleplate",
          cost: 2500,
          id: 111,
          eventOnlyItem: false,
          wowheadId: 215311,
          type: "plate",
        },
        {
          name: "Swarmbreaker's Battleplate",
          cost: 2500,
          id: 112,
          eventOnlyItem: false,
          wowheadId: 215312,
          type: "plate",
        },
      ],
    },
    {
      name: "Jakkus",
      description: "Class Apparel",
      id: 4,
      items: [
        {
          name: "Mage Arsenal",
          cost: 3000,
          id: 113,
          eventOnlyItem: true,
          wowheadId: 217823,
          class: "mage",
        },
        {
          name: "Priest Arsenal",
          cost: 3000,
          id: 114,
          eventOnlyItem: true,
          wowheadId: 217831,
          class: "priest",
        },
        {
          name: "Warlock Arsenal",
          cost: 3000,
          id: 115,
          eventOnlyItem: true,
          wowheadId: 217826,
          class: "warlock",
        },
        {
          name: "Druid Arsenal",
          cost: 3000,
          id: 116,
          eventOnlyItem: true,
          wowheadId: 217829,
          class: "druid",
        },
        {
          name: "Monk Arsenal",
          cost: 3000,
          id: 117,
          eventOnlyItem: true,
          wowheadId: 217827,
          class: "monk",
        },
        {
          name: "Rogue Arsenal",
          cost: 3000,
          id: 118,
          eventOnlyItem: true,
          wowheadId: 217830,
          class: "rogue",
        },
        {
          name: "Demon Hunter Arsenal",
          cost: 3000,
          id: 119,
          eventOnlyItem: true,
          wowheadId: 217828,
          class: "demon hunter",
        },
        {
          name: "Hunter Arsenal",
          cost: 3000,
          id: 120,
          eventOnlyItem: true,
          wowheadId: 217820,
          class: "hunter",
        },
        {
          name: "Shaman Arsenal",
          cost: 3000,
          id: 121,
          eventOnlyItem: true,
          wowheadId: 217819,
          class: "shaman",
        },
        {
          name: "Evoker Arsenal",
          cost: 3000,
          id: 122,
          eventOnlyItem: true,
          wowheadId: 217821,
          class: "evoker",
        },
        {
          name: "Death Knight Arsenal",
          cost: 3000,
          id: 123,
          eventOnlyItem: true,
          wowheadId: 217824,
          class: "death knight",
        },
        {
          name: "Paladin Arsenal",
          cost: 3000,
          id: 124,
          eventOnlyItem: true,
          wowheadId: 217832,
          class: "paladin",
        },
        {
          name: "Warrior Arsenal",
          cost: 3000,
          id: 125,
          eventOnlyItem: true,
          wowheadId: 217825,
          class: "warrior",
        },
        {
          name: "Mage Ensemble",
          cost: 4000,
          id: 126,
          eventOnlyItem: true,
          wowheadId: 217836,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Priest Ensemble",
          cost: 4000,
          id: 127,
          eventOnlyItem: true,
          wowheadId: 217845,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Warlock Ensemble",
          cost: 4000,
          id: 128,
          eventOnlyItem: true,
          wowheadId: 217839,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Druid Ensemble",
          cost: 4000,
          id: 129,
          eventOnlyItem: true,
          wowheadId: 217843,
          type: "leather",
          class: "druid",
        },
        {
          name: "Monk Ensemble",
          cost: 4000,
          id: 130,
          eventOnlyItem: true,
          wowheadId: 217841,
          type: "leather",
          class: "monk",
        },
        {
          name: "Rogue Ensemble",
          cost: 4000,
          id: 131,
          eventOnlyItem: true,
          wowheadId: 217844,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Demon Hunter Ensemble",
          cost: 4000,
          id: 132,
          eventOnlyItem: true,
          wowheadId: 217842,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Hunter Ensemble",
          cost: 4000,
          id: 133,
          eventOnlyItem: true,
          wowheadId: 217834,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Shaman Ensemble",
          cost: 4000,
          id: 134,
          eventOnlyItem: true,
          wowheadId: 217833,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Evoker Ensemble",
          cost: 4000,
          id: 135,
          eventOnlyItem: true,
          wowheadId: 217835,
          type: "mail",
          class: "evoker",
        },
        {
          name: "Death Knight Ensemble",
          cost: 4000,
          id: 136,
          eventOnlyItem: true,
          wowheadId: 217837,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Paladin Ensemble",
          cost: 4000,
          id: 137,
          eventOnlyItem: true,
          wowheadId: 217846,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Warrior Ensemble",
          cost: 4000,
          id: 138,
          eventOnlyItem: true,
          wowheadId: 217838,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Larah",
      description: "World Apparel",
      id: 5,
      items: [
        {
          name: "Spirit-Waker's Vestments",
          cost: 750,
          id: 139,
          eventOnlyItem: false,
          wowheadId: 215183,
          type: "cloth",
        },
        {
          name: "Spirit-Waker's Vestments",
          cost: 750,
          id: 140,
          eventOnlyItem: false,
          wowheadId: 215184,
          type: "cloth",
        },
        {
          name: "Spirit-Waker's Vestments",
          cost: 750,
          id: 141,
          eventOnlyItem: false,
          wowheadId: 215185,
          type: "cloth",
        },
        {
          name: "Mistwalker's Vestments",
          cost: 750,
          id: 142,
          eventOnlyItem: false,
          wowheadId: 215186,
          type: "cloth",
        },
        {
          name: "Mistwalker's Vestments",
          cost: 750,
          id: 143,
          eventOnlyItem: false,
          wowheadId: 215187,
          type: "cloth",
        },
        {
          name: "Mistwalker's Vestments",
          cost: 750,
          id: 144,
          eventOnlyItem: false,
          wowheadId: 215188,
          type: "cloth",
        },
        {
          name: "Vestments of the Eternal Dynasty",
          cost: 2000,
          id: 145,
          eventOnlyItem: false,
          wowheadId: 215216,
          type: "cloth",
        },
        {
          name: "Vestments of the Eternal Dynasty",
          cost: 2000,
          id: 146,
          eventOnlyItem: false,
          wowheadId: 215217,
          type: "cloth",
        },
        {
          name: "Vestments of the Eternal Dynasty",
          cost: 2000,
          id: 147,
          eventOnlyItem: false,
          wowheadId: 215218,
          type: "cloth",
        },
        {
          name: "Thunderpaw Battlegear",
          cost: 750,
          id: 148,
          eventOnlyItem: false,
          wowheadId: 215225,
          type: "leather",
        },
        {
          name: "Thunderpaw Battlegear",
          cost: 750,
          id: 149,
          eventOnlyItem: false,
          wowheadId: 215226,
          type: "leather",
        },
        {
          name: "Thunderpaw Battlegear",
          cost: 750,
          id: 150,
          eventOnlyItem: false,
          wowheadId: 215227,
          type: "leather",
        },
        {
          name: "Thunderpaw Battlegear",
          cost: 750,
          id: 151,
          eventOnlyItem: false,
          wowheadId: 215228,
          type: "leather",
        },
        {
          name: "Mistveil Leathers",
          cost: 750,
          id: 152,
          eventOnlyItem: false,
          wowheadId: 215229,
          type: "leather",
        },
        {
          name: "Mistveil Leathers",
          cost: 750,
          id: 153,
          eventOnlyItem: false,
          wowheadId: 215230,
          type: "leather",
        },
        {
          name: "Mistveil Leathers",
          cost: 750,
          id: 154,
          eventOnlyItem: false,
          wowheadId: 215231,
          type: "leather",
        },
        {
          name: "Mistveil Leathers",
          cost: 750,
          id: 155,
          eventOnlyItem: false,
          wowheadId: 215232,
          type: "leather",
        },
        {
          name: "Snowdrift Battlegear",
          cost: 2000,
          id: 156,
          eventOnlyItem: false,
          wowheadId: 215269,
          type: "leather",
        },
        {
          name: "Snowdrift Battlegear",
          cost: 2000,
          id: 157,
          eventOnlyItem: false,
          wowheadId: 215270,
          type: "leather",
        },
        {
          name: "Snowdrift Battlegear",
          cost: 2000,
          id: 158,
          eventOnlyItem: false,
          wowheadId: 215271,
          type: "leather",
        },
        {
          name: "Trailseeker's Laminar Armor",
          cost: 750,
          id: 159,
          eventOnlyItem: false,
          wowheadId: 215278,
          type: "mail",
        },
        {
          name: "Trailseeker's Laminar Armor",
          cost: 750,
          id: 160,
          eventOnlyItem: false,
          wowheadId: 215279,
          type: "mail",
        },
        {
          name: "Trailseeker's Laminar Armor",
          cost: 750,
          id: 161,
          eventOnlyItem: false,
          wowheadId: 215280,
          type: "mail",
        },
        {
          name: "Trailseeker's Laminar Armor",
          cost: 750,
          id: 162,
          eventOnlyItem: false,
          wowheadId: 215281,
          type: "mail",
        },
        {
          name: "Dawnwatcher's Scale Armor",
          cost: 750,
          id: 163,
          eventOnlyItem: false,
          wowheadId: 215282,
          type: "mail",
        },
        {
          name: "Dawnwatcher's Scale Armor",
          cost: 750,
          id: 164,
          eventOnlyItem: false,
          wowheadId: 215283,
          type: "mail",
        },
        {
          name: "Dawnwatcher's Scale Armor",
          cost: 750,
          id: 165,
          eventOnlyItem: false,
          wowheadId: 215284,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia",
          cost: 2000,
          id: 166,
          eventOnlyItem: false,
          wowheadId: 215306,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia",
          cost: 2000,
          id: 167,
          eventOnlyItem: false,
          wowheadId: 215307,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia",
          cost: 2000,
          id: 168,
          eventOnlyItem: false,
          wowheadId: 215308,
          type: "mail",
        },
        {
          name: "Jade Guardian's Regalia",
          cost: 2000,
          id: 169,
          eventOnlyItem: false,
          wowheadId: 215309,
          type: "mail",
        },
        {
          name: "Spiritguard's Warplate",
          cost: 750,
          id: 170,
          eventOnlyItem: false,
          wowheadId: 215313,
          type: "plate",
        },
        {
          name: "Spiritguard's Warplate",
          cost: 750,
          id: 171,
          eventOnlyItem: false,
          wowheadId: 215314,
          type: "plate",
        },
        {
          name: "Spiritguard's Warplate",
          cost: 750,
          id: 172,
          eventOnlyItem: false,
          wowheadId: 215315,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate",
          cost: 750,
          id: 173,
          eventOnlyItem: false,
          wowheadId: 215316,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate",
          cost: 750,
          id: 174,
          eventOnlyItem: false,
          wowheadId: 215317,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate",
          cost: 750,
          id: 175,
          eventOnlyItem: false,
          wowheadId: 215318,
          type: "plate",
        },
        {
          name: "Shan'ze Warplate",
          cost: 750,
          id: 176,
          eventOnlyItem: false,
          wowheadId: 215319,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate",
          cost: 2000,
          id: 177,
          eventOnlyItem: false,
          wowheadId: 215348,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate",
          cost: 2000,
          id: 178,
          eventOnlyItem: false,
          wowheadId: 215349,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate",
          cost: 2000,
          id: 179,
          eventOnlyItem: false,
          wowheadId: 215350,
          type: "plate",
        },
        {
          name: "Gatecrasher's Battleplate",
          cost: 2000,
          id: 180,
          eventOnlyItem: false,
          wowheadId: 215351,
          type: "plate",
        },
        {
          name: "Guise of the Shado-Pan",
          cost: 2500,
          id: 181,
          eventOnlyItem: true,
          wowheadId: 215219,
        },
        {
          name: "Guise of the Shado-Pan",
          cost: 2500,
          id: 182,
          eventOnlyItem: true,
          wowheadId: 215220,
        },
        {
          name: "Tian Monastery Clothing",
          cost: 1250,
          id: 183,
          eventOnlyItem: true,
          wowheadId: 215238,
        },
        {
          name: "Tian Monastery Clothing",
          cost: 1250,
          id: 184,
          eventOnlyItem: true,
          wowheadId: 215239,
        },
        {
          name: "Tian Monastery Clothing",
          cost: 1250,
          id: 185,
          eventOnlyItem: true,
          wowheadId: 215240,
        },
        {
          name: "Kor'kron Shaman Vestments",
          cost: 2500,
          id: 186,
          eventOnlyItem: true,
          wowheadId: 215275,
        },
        {
          name: "Kor'kron Shaman Vestments",
          cost: 2500,
          id: 187,
          eventOnlyItem: true,
          wowheadId: 215276,
        },
        {
          name: "Kor'kron Shaman Vestments",
          cost: 2500,
          id: 188,
          eventOnlyItem: true,
          wowheadId: 215277,
        },
        {
          name: "Sun Pearl Clothing",
          cost: 1250,
          id: 189,
          eventOnlyItem: true,
          wowheadId: 215285,
        },
        {
          name: "Sun Pearl Clothing",
          cost: 1250,
          id: 190,
          eventOnlyItem: true,
          wowheadId: 215286,
        },
        {
          name: "Sun Pearl Clothing",
          cost: 1250,
          id: 191,
          eventOnlyItem: true,
          wowheadId: 215287,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 192,
          eventOnlyItem: true,
          wowheadId: 215352,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 193,
          eventOnlyItem: true,
          wowheadId: 215353,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 194,
          eventOnlyItem: true,
          wowheadId: 215354,
        },
        {
          name: "Robes of Quiet Reflection",
          cost: 1250,
          id: 195,
          eventOnlyItem: true,
          wowheadId: 215355,
        },
        {
          name: "Vestments of Serenity",
          cost: 1250,
          id: 196,
          eventOnlyItem: true,
          wowheadId: 215356,
        },
        {
          name: "Vestments of Serenity",
          cost: 1250,
          id: 197,
          eventOnlyItem: true,
          wowheadId: 215357,
        },
        {
          name: "Vestments of Serenity",
          cost: 1250,
          id: 198,
          eventOnlyItem: true,
          wowheadId: 215358,
        },
      ],
    },
    {
      name: "Hemet XVII",
      description: "Beastmaster",
      id: 6,
      items: [],
    },
    {
      name: "Horos",
      description: "Rare Collections",
      id: 7,
      items: [],
    },
  ],
};

export default bronze;
