import { BronzeType } from "../_interfaces/Bronze.interface";

const bronze: BronzeType = {
  vendors: [
    {
      name: "Aeonicus",
      description: "Raid Finder Apparel",
      id: 10,
      items: [
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 20000,
          id: 1000,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 20000,
          id: 1001,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 20000,
          id: 1002,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 20000,
          id: 1003,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 20000,
          id: 1004,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 20000,
          id: 1005,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 20000,
          id: 1006,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 20000,
          id: 1007,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements",
          cost: 20000,
          id: 1008,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 20000,
          id: 1009,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 20000,
          id: 1010,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 20000,
          id: 1011,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Funerary Plate of the Chosen Dead",
          cost: 20000,
          id: 1012,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
        },
        {
          name: "Ensemble: Chains of the Chosen Dead",
          cost: 20000,
          id: 1013,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
        },
        {
          name: "Ensemble: Garb of the Chosen Dead",
          cost: 20000,
          id: 1014,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
        },
        {
          name: "Ensemble: Regalia of the Chosen Dead",
          cost: 20000,
          id: 1015,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 20000,
          id: 1016,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 20000,
          id: 1017,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 20000,
          id: 1018,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 20000,
          id: 1019,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 20000,
          id: 1020,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 20000,
          id: 1021,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 20000,
          id: 1022,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 20000,
          id: 1023,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 20000,
          id: 1024,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 20000,
          id: 1025,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 20000,
          id: 1026,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 20000,
          id: 1027,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 20000,
          id: 1028,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 20000,
          id: 1029,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 20000,
          id: 1030,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 20000,
          id: 1031,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 20000,
          id: 1032,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 20000,
          id: 1033,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 20000,
          id: 1034,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 20000,
          id: 1035,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 20000,
          id: 1036,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 20000,
          id: 1037,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 20000,
          id: 1038,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 20000,
          id: 1039,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Durus",
      description: "Normal Raid Apparel",
      id: 11,
      items: [
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 20000,
          id: 1040,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 20000,
          id: 1041,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 20000,
          id: 1042,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 20000,
          id: 1043,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 20000,
          id: 1044,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 20000,
          id: 1045,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 20000,
          id: 1046,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 20000,
          id: 1047,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements",
          cost: 20000,
          id: 1048,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 20000,
          id: 1049,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 20000,
          id: 1050,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 20000,
          id: 1051,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 20000,
          id: 1052,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 20000,
          id: 1053,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 20000,
          id: 1054,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 20000,
          id: 1055,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 20000,
          id: 1056,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 20000,
          id: 1057,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 20000,
          id: 1058,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 20000,
          id: 1059,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 20000,
          id: 1060,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 20000,
          id: 1061,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 20000,
          id: 1062,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 20000,
          id: 1063,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 20000,
          id: 1064,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 20000,
          id: 1065,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 20000,
          id: 1066,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 20000,
          id: 1067,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 20000,
          id: 1068,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 20000,
          id: 1069,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 20000,
          id: 1070,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 20000,
          id: 1071,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 20000,
          id: 1072,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 20000,
          id: 1073,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 20000,
          id: 1074,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 20000,
          id: 1075,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Sacerdormu",
      description: "Heroic Raid Apparel",
      id: 12,
      items: [
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 20000,
          id: 1076,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 20000,
          id: 1077,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 20000,
          id: 1078,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 20000,
          id: 1079,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 20000,
          id: 1080,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 20000,
          id: 1081,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 20000,
          id: 1082,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 20000,
          id: 1083,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements (Ice)",
          cost: 20000,
          id: 1084,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements (Felfire)",
          cost: 20000,
          id: 1085,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 20000,
          id: 1086,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 20000,
          id: 1087,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 20000,
          id: 1088,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 20000,
          id: 1089,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 20000,
          id: 1090,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 20000,
          id: 1091,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 20000,
          id: 1092,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 20000,
          id: 1093,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 20000,
          id: 1094,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 20000,
          id: 1095,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 20000,
          id: 1096,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 20000,
          id: 1097,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 20000,
          id: 1098,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 20000,
          id: 1099,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 20000,
          id: 1100,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 20000,
          id: 1101,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 20000,
          id: 1102,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 20000,
          id: 1103,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 20000,
          id: 1104,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 20000,
          id: 1105,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 20000,
          id: 1106,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 20000,
          id: 1107,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 20000,
          id: 1108,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 20000,
          id: 1109,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 20000,
          id: 1110,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 20000,
          id: 1111,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 20000,
          id: 1112,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Pythagorus",
      description: "Mythic Raid Apparel",
      id: 13,
      items: [
        {
          name: "The First Satyr's Spaulders",
          cost: 30000,
          id: 1113,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Hammer of Vigilance",
          cost: 30000,
          id: 1114,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Scythe of the Unmaker",
          cost: 30000,
          id: 1115,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Taeshalach",
          cost: 30000,
          id: 1116,
          eventOnlyItem: false,
          wowheadId: 241587,
        },
        {
          name: "Ensemble: Regalia of Everburning Knowledge",
          cost: 30000,
          id: 1117,
          eventOnlyItem: false,
          wowheadId: 241587,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of the Purifier",
          cost: 30000,
          id: 1118,
          eventOnlyItem: false,
          wowheadId: 241583,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Legacy of Azj'Aqir",
          cost: 30000,
          id: 1119,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Vestment of Second Sight",
          cost: 30000,
          id: 1120,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Garb of the Astral Warden",
          cost: 30000,
          id: 1121,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Vestments of Enveloped Dissonance",
          cost: 30000,
          id: 1122,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Doomblade Battlegear",
          cost: 30000,
          id: 1123,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Eagletalon Battlegear",
          cost: 30000,
          id: 1124,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of Shackled Elements",
          cost: 30000,
          id: 1125,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwyrm Battleplate",
          cost: 30000,
          id: 1126,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Battleplate of the Highlord",
          cost: 30000,
          id: 1127,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Warplate of the Obsidian Aspect",
          cost: 30000,
          id: 1128,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Regalia of the Arcane Tempest",
          cost: 30000,
          id: 1129,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Vestments of Blind Absolution",
          cost: 30000,
          id: 1130,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Diabolic Raiment",
          cost: 30000,
          id: 1131,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Demonbane Armor",
          cost: 30000,
          id: 1132,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Stormheart Raiment",
          cost: 30000,
          id: 1133,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Xuen's Battlegear",
          cost: 30000,
          id: 1134,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Fanged Slayer's Armor",
          cost: 30000,
          id: 1135,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Wildstalker Armor",
          cost: 30000,
          id: 1136,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Regalia of the Skybreaker",
          cost: 30000,
          id: 1137,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Gravewarden Armaments",
          cost: 30000,
          id: 1138,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Radiant Lightbringer Armor",
          cost: 30000,
          id: 1139,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Titanic Onslaught Armor",
          cost: 30000,
          id: 1140,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
        {
          name: "Ensemble: Runebound Regalia",
          cost: 30000,
          id: 1141,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "mage",
        },
        {
          name: "Ensemble: Gilded Seraph's Raiment",
          cost: 30000,
          id: 1142,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "priest",
        },
        {
          name: "Ensemble: Grim Inquisitor's Regalia",
          cost: 30000,
          id: 1143,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "cloth",
          class: "warlock",
        },
        {
          name: "Ensemble: Felreaper Vestments",
          cost: 30000,
          id: 1144,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "demon hunter",
        },
        {
          name: "Ensemble: Bearmantle Battlegear",
          cost: 30000,
          id: 1145,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "druid",
        },
        {
          name: "Ensemble: Chi-Ji's Battlegear",
          cost: 30000,
          id: 1146,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "monk",
        },
        {
          name: "Ensemble: Regalia of the Dashing Scoundrel",
          cost: 30000,
          id: 1147,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "leather",
          class: "rogue",
        },
        {
          name: "Ensemble: Serpentstalker Guise",
          cost: 30000,
          id: 1148,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "hunter",
        },
        {
          name: "Ensemble: Garb of Venerated Spirits",
          cost: 30000,
          id: 1149,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "mail",
          class: "shaman",
        },
        {
          name: "Ensemble: Dreadwake Armor",
          cost: 30000,
          id: 1150,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "death knight",
        },
        {
          name: "Ensemble: Light's Vanguard Battleplate",
          cost: 30000,
          id: 1151,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "paladin",
        },
        {
          name: "Ensemble: Juggernaut Battlegear",
          cost: 30000,
          id: 1152,
          eventOnlyItem: false,
          wowheadId: 0,
          type: "plate",
          class: "warrior",
        },
      ],
    },
    {
      name: "Arturos",
      description: "Dungeon Apparel",
      id: 14,
      items: [
        {
          name: "Ensemble: Seawitch's Terrorcloth",
          cost: 15000,
          id: 1153,
          eventOnlyItem: false,
          wowheadId: 241439,
          type: "cloth",
        },
        {
          name: "Ensemble: Nighthide Coat",
          cost: 15000,
          id: 1154,
          eventOnlyItem: false,
          wowheadId: 241436,
          type: "leather",
        },
        {
          name: "Ensemble: Chains of Nightmare's Embrace",
          cost: 15000,
          id: 1154,
          eventOnlyItem: false,
          wowheadId: 241434,
          type: "mail",
        },
        {
          name: "Ensemble: Suramar Silver Plating",
          cost: 15000,
          id: 1155,
          eventOnlyItem: false,
          wowheadId: 241431,
          type: "plate",
        },
        {
          name: "Ensemble: Vesture of Borrowed Souls",
          cost: 15000,
          id: 1156,
          eventOnlyItem: false,
          wowheadId: 241428,
          type: "cloth",
        },
        {
          name: "Ensemble: Sanguine Oath Vestments",
          cost: 15000,
          id: 1157,
          eventOnlyItem: false,
          wowheadId: 241427,
          type: "cloth",
        },
        {
          name: "Ensemble: Bindings of Hungering Flesh",
          cost: 15000,
          id: 1158,
          eventOnlyItem: false,
          wowheadId: 241425,
          type: "leather",
        },
        {
          name: "Ensemble: Thirsting Hides",
          cost: 15000,
          id: 1159,
          eventOnlyItem: false,
          wowheadId: 241424,
          type: "cloth",
        },
        {
          name: "Ensemble: Armor of the Skyfather's Chosen",
          cost: 15000,
          id: 1160,
          eventOnlyItem: false,
          wowheadId: 241422,
          type: "mail",
        },
        {
          name: "Ensemble: Ravensteel Mail",
          cost: 15000,
          id: 1161,
          eventOnlyItem: false,
          wowheadId: 241421,
          type: "mail",
        },
        {
          name: "Ensemble: Honorforged Valorplate",
          cost: 15000,
          id: 1162,
          eventOnlyItem: false,
          wowheadId: 241419,
          type: "plate",
        },
        {
          name: "Ensemble: Bloodforged Battleplate",
          cost: 15000,
          id: 1163,
          eventOnlyItem: false,
          wowheadId: 241418,
          type: "plate",
        },
        {
          name: "Ensemble: Nightforged Felplate",
          cost: 15000,
          id: 1164,
          eventOnlyItem: false,
          wowheadId: 241417,
          type: "plate",
        },
        {
          name: "Ensemble: Raiment of Night Eternal",
          cost: 15000,
          id: 1165,
          eventOnlyItem: false,
          wowheadId: 241426,
          type: "cloth",
        },
        {
          name: "Ensemble: Guise of the Nightstalker",
          cost: 15000,
          id: 1166,
          eventOnlyItem: false,
          wowheadId: 241423,
          type: "leather",
        },
        {
          name: "Ensemble: Scalemail of Devouring Night",
          cost: 15000,
          id: 1167,
          eventOnlyItem: false,
          wowheadId: 241420,
          type: "mail",
        },
      ],
    },
    {
      name: "Jakkus",
      description: "Class Mounts",
      id: 15,
      items: [
        {
          name: "Reins of the Highlord's Felscorned Charger",
          cost: 20000,
          id: 1168,
          eventOnlyItem: true,
          wowheadId: 253028,
          class: "paladin",
        },
        {
          name: "Iron Reins of the Felscorned War Wyrm",
          cost: 20000,
          id: 1169,
          eventOnlyItem: true,
          wowheadId: 253033,
          class: "warrior",
        },
        {
          name: "Felscorned Reins of the Vilebrood Vanquisher",
          cost: 20000,
          id: 1170,
          eventOnlyItem: true,
          wowheadId: 252954,
          class: "death knight",
        },
        {
          name: "Reins of the Felscorned Wolfhawk",
          cost: 20000,
          id: 1171,
          eventOnlyItem: true,
          wowheadId: 253025,
          class: "hunter",
        },
        {
          name: "Felscorned Tempest Totem",
          cost: 20000,
          id: 1172,
          eventOnlyItem: true,
          wowheadId: 253031,
          class: "shaman",
        },
        {
          name: "Shadowblade's Reins of Felscorned Portent",
          cost: 20000,
          id: 1173,
          eventOnlyItem: true,
          wowheadId: 253030,
          class: "rogue",
        },
        {
          name: "Felscorned Grandmaster's Bell",
          cost: 20000,
          id: 1174,
          eventOnlyItem: true,
          wowheadId: 253027,
          class: "monk",
        },
        {
          name: "Feldruid's Scornwing Idol",
          cost: 20000,
          id: 1175,
          eventOnlyItem: true,
          wowheadId: 253024,
          class: "druid",
        },
        {
          name: "Slayer's Reins of the Felscorned Shrieker",
          cost: 20000,
          id: 1176,
          eventOnlyItem: true,
          wowheadId: 253013,
          class: "demon hunter",
        },
        {
          name: "Felscorned Seeker's Whistle",
          cost: 20000,
          id: 1177,
          eventOnlyItem: true,
          wowheadId: 253029,
          class: "priest",
        },
        {
          name: "Felscorned Reins of the Netherlord's Dreadsteed",
          cost: 20000,
          id: 1178,
          eventOnlyItem: true,
          wowheadId: 253032,
          class: "warlock",
        },
        {
          name: "Archmage's Felscorned Disc",
          cost: 20000,
          id: 1179,
          eventOnlyItem: true,
          wowheadId: 253026,
          class: "mage",
        },
      ],
    },
    {
      name: "Larah",
      description: "World Apparel",
      id: 16,
      items: [
        {
          name: "Ensemble: Fel-Infused Cloth Armor",
          cost: 15000,
          id: 1180,
          eventOnlyItem: false,
          wowheadId: 139170,
          type: "cloth",
        },
        {
          name: "Ensemble: Felshroud Leather Armor",
          cost: 15000,
          id: 1181,
          eventOnlyItem: false,
          wowheadId: 139169,
          type: "leather",
        },
        {
          name: "Ensemble: Fel-Chain Mail Armor",
          cost: 15000,
          id: 1182,
          eventOnlyItem: false,
          wowheadId: 139168,
          type: "mail",
        },
        {
          name: "Ensemble: Felforged Plate Armor",
          cost: 15000,
          id: 1183,
          eventOnlyItem: false,
          wowheadId: 139167,
          type: "plate",
        },
        {
          name: "Ensemble: Vestments of the Manasinged",
          cost: 15000,
          id: 1184,
          eventOnlyItem: false,
          wowheadId: 241440,
          type: "cloth",
        },
        {
          name: "Ensemble: Moonfall Robes",
          cost: 15000,
          id: 1185,
          eventOnlyItem: false,
          wowheadId: 241438,
          type: "cloth",
        },
        {
          name: "Ensemble: Battlegear of the Dreadhide Stalker",
          cost: 15000,
          id: 1186,
          eventOnlyItem: false,
          wowheadId: 241437,
          type: "leather",
        },
        {
          name: "Ensemble: Ambervale Bonehide",
          cost: 15000,
          id: 1187,
          eventOnlyItem: false,
          wowheadId: 241435,
          type: "leather",
        },
        {
          name: "Ensemble: Chains of Helheim",
          cost: 15000,
          id: 1188,
          eventOnlyItem: false,
          wowheadId: 241433,
          type: "mail",
        },
        {
          name: "Ensemble: Darkwatcher Bindings",
          cost: 15000,
          id: 1189,
          eventOnlyItem: false,
          wowheadId: 241432,
          type: "mail",
        },
        {
          name: "Ensemble: Jandvik Diver's Metal",
          cost: 15000,
          id: 1190,
          eventOnlyItem: false,
          wowheadId: 241430,
          type: "plate",
        },
        {
          name: "Ensemble: Leyline Defender's Sunplate Armor",
          cost: 15000,
          id: 1191,
          eventOnlyItem: false,
          wowheadId: 241429,
          type: "plate",
        },
        {
          name: "Ensemble: Regalia of the Hrydshal Runespeaker",
          cost: 15000,
          id: 1192,
          eventOnlyItem: false,
          wowheadId: 241384,
          type: "cloth",
        },
        {
          name: "Ensemble: Crescent Vale Raiment",
          cost: 15000,
          id: 1193,
          eventOnlyItem: false,
          wowheadId: 241383,
          type: "cloth",
        },
        {
          name: "Ensemble: Wine-dark Royal Robes",
          cost: 15000,
          id: 1194,
          eventOnlyItem: false,
          wowheadId: 241382,
          type: "cloth",
        },
        {
          name: "Ensemble: Leyline Scholar's Regalia",
          cost: 15000,
          id: 1195,
          eventOnlyItem: false,
          wowheadId: 241381,
          type: "cloth",
        },
        {
          name: "Ensemble: Highmountain Hides",
          cost: 15000,
          id: 1196,
          eventOnlyItem: false,
          wowheadId: 241380,
          type: "leather",
        },
        {
          name: "Ensemble: Haustvelt Leathers",
          cost: 15000,
          id: 1197,
          eventOnlyItem: false,
          wowheadId: 241379,
          type: "leather",
        },
        {
          name: "Ensemble: Sablehide Vestments",
          cost: 15000,
          id: 1198,
          eventOnlyItem: false,
          wowheadId: 241378,
          type: "leather",
        },
        {
          name: "Ensemble: Llothien Prowler's Kit",
          cost: 15000,
          id: 1199,
          eventOnlyItem: false,
          wowheadId: 241377,
          type: "leather",
        },
        {
          name: "Ensemble: Scavenged Chains of Karazhan",
          cost: 15000,
          id: 1200,
          eventOnlyItem: false,
          wowheadId: 241594,
          type: "mail",
        },
        {
          name: "Ensemble: Dreadthorn Battlegear",
          cost: 15000,
          id: 1201,
          eventOnlyItem: false,
          wowheadId: 241376,
          type: "mail",
        },
        {
          name: "Ensemble: Scales of Remembered Eternity",
          cost: 15000,
          id: 1202,
          eventOnlyItem: false,
          wowheadId: 241375,
          type: "mail",
        },
        {
          name: "Ensemble: Stormborn Laminar Armor",
          cost: 15000,
          id: 1203,
          eventOnlyItem: false,
          wowheadId: 241374,
          type: "mail",
        },
        {
          name: "Ensemble: Highmountain Riverscales",
          cost: 15000,
          id: 1204,
          eventOnlyItem: false,
          wowheadId: 241373,
          type: "mail",
        },
        {
          name: "Ensemble: Thunderpeak Boneguards",
          cost: 15000,
          id: 1205,
          eventOnlyItem: false,
          wowheadId: 241372,
          type: "plate",
        },
        {
          name: "Ensemble: Nar'thalas Graduate's Trim",
          cost: 15000,
          id: 1206,
          eventOnlyItem: false,
          wowheadId: 241371,
          type: "plate",
        },
        {
          name: "Ensemble: Kal'delar Battleplate",
          cost: 15000,
          id: 1207,
          eventOnlyItem: false,
          wowheadId: 241370,
          type: "plate",
        },
        {
          name: "Ensemble: Vrykul Funereal Regalia",
          cost: 15000,
          id: 1208,
          eventOnlyItem: false,
          wowheadId: 241369,
          type: "plate",
        },
        {
          name: "Ensemble: Riven Priesthood Regalia",
          cost: 15000,
          id: 1209,
          eventOnlyItem: false,
          wowheadId: 241364,
          type: "cloth",
        },
        {
          name: "Ensemble: Lunarblight Leathers",
          cost: 15000,
          id: 1210,
          eventOnlyItem: false,
          wowheadId: 241363,
          type: "leather",
        },
        {
          name: "Ensemble: Shrinebreaker's Battlegear",
          cost: 15000,
          id: 1211,
          eventOnlyItem: false,
          wowheadId: 241362,
          type: "mail",
        },
        {
          name: "Ensemble: Moonshatter Warplate",
          cost: 15000,
          id: 1212,
          eventOnlyItem: false,
          wowheadId: 241361,
          type: "plate",
        },
        {
          name: "Ensemble: Vileweave Vestments",
          cost: 15000,
          id: 1213,
          eventOnlyItem: false,
          wowheadId: 241444,
          type: "cloth",
        },
        {
          name: "Ensemble: Netherfiend Battlegear",
          cost: 15000,
          id: 1214,
          eventOnlyItem: false,
          wowheadId: 241443,
          type: "leather",
        },
        {
          name: "Ensemble: Ered'ruin Scalemail",
          cost: 15000,
          id: 1215,
          eventOnlyItem: false,
          wowheadId: 241442,
          type: "mail",
        },
        {
          name: "Ensemble: Xorothian Plate Armor",
          cost: 15000,
          id: 1216,
          eventOnlyItem: false,
          wowheadId: 241441,
          type: "plate",
        },
        {
          name: "Ensemble: Garothi Battleplate",
          cost: 15000,
          id: 1217,
          eventOnlyItem: false,
          wowheadId: 241359,
          type: "plate",
        },
        {
          name: "Ensemble: Doomsinger's Cloth Armor",
          cost: 15000,
          id: 1218,
          eventOnlyItem: false,
          wowheadId: 241368,
          type: "cloth",
        },
        {
          name: "Ensemble: Arinor Keeper's Leather Armor",
          cost: 15000,
          id: 1219,
          eventOnlyItem: false,
          wowheadId: 241367,
          type: "leather",
        },
        {
          name: "Ensemble: Oronaar Disciple's Mail Armor",
          cost: 15000,
          id: 1220,
          eventOnlyItem: false,
          wowheadId: 241366,
          type: "mail",
        },
        {
          name: "Ensemble: Praetorium Guard's Plate Armor",
          cost: 15000,
          id: 1221,
          eventOnlyItem: false,
          wowheadId: 241365,
          type: "plate",
        },
        {
          name: "Ensemble: Stygian Hides",
          cost: 15000,
          id: 1222,
          eventOnlyItem: false,
          wowheadId: 241391,
          type: "leather",
        },
        {
          name: "Ensemble: Zealous Felslingers Battle Armor",
          cost: 15000,
          id: 1223,
          eventOnlyItem: false,
          wowheadId: 253594,
        },
        {
          name: "Ensemble: World-Defiler's Battle Armor",
          cost: 15000,
          id: 1224,
          eventOnlyItem: false,
          wowheadId: 253588,
        },
        {
          name: "Ensemble: Eredath Lightseeker's Regalia",
          cost: 15000,
          id: 1225,
          eventOnlyItem: false,
          wowheadId: 254754,
        },
        {
          name: "Ensemble: Forgotten Conservatory Clothes",
          cost: 15000,
          id: 1226,
          eventOnlyItem: false,
          wowheadId: 254753,
        },
        {
          name: "Ensemble: Triumvirate High Guard's Battlegear",
          cost: 15000,
          id: 1227,
          eventOnlyItem: false,
          wowheadId: 254752,
        },
      ],
    },
    {
      name: "Hemet Nesingwary XVII",
      description: "Beastmaster",
      id: 17,
      items: [
        {
          name: "Reins of the Illidari Dreadstalker",
          cost: 10000,
          id: 1228,
          eventOnlyItem: true,
          wowheadId: 250428,
        },
        {
          name: "Reins of the Illidari Blightstalker",
          cost: 10000,
          id: 1229,
          eventOnlyItem: true,
          wowheadId: 250427,
        },
        {
          name: "Reins of the Highland Elderhorn",
          cost: 10000,
          id: 1230,
          eventOnlyItem: true,
          wowheadId: 250429,
        },
        {
          name: "Reins of the Treetop Highmountain Eagle",
          cost: 10000,
          id: 1231,
          eventOnlyItem: true,
          wowheadId: 250723,
        },
        {
          name: "Reins of the Snowy Highmountain Eagle",
          cost: 10000,
          id: 1232,
          eventOnlyItem: true,
          wowheadId: 250721,
        },
        {
          name: "Reins of the Wretched Fel Bat",
          cost: 10000,
          id: 1233,
          eventOnlyItem: true,
          wowheadId: 239687,
        },
        {
          name: "Reins of the Ashplague Fel Bat",
          cost: 10000,
          id: 1234,
          eventOnlyItem: true,
          wowheadId: 239667,
        },
        {
          name: "Reins of the Bloodhunter Fel Bat",
          cost: 10000,
          id: 1235,
          eventOnlyItem: true,
          wowheadId: 239665,
        },
        {
          name: "Reins of the Gloomdark Nightmare",
          cost: 10000,
          id: 1236,
          eventOnlyItem: true,
          wowheadId: 250757,
        },
        {
          name: "Reins of the Turquoise Courser",
          cost: 10000,
          id: 1237,
          eventOnlyItem: true,
          wowheadId: 250756,
        },
        {
          name: "Reins of the Golden Sunrunner",
          cost: 10000,
          id: 1238,
          eventOnlyItem: true,
          wowheadId: 250752,
        },
        {
          name: "Reins of the Twilight Courser",
          cost: 10000,
          id: 1239,
          eventOnlyItem: true,
          wowheadId: 250751,
        },
        {
          name: "Reins of the Brimstone Courser",
          cost: 10000,
          id: 1240,
          eventOnlyItem: true,
          wowheadId: 251795,
        },
        {
          name: "Reins of the Chestnut Courser",
          cost: 10000,
          id: 1241,
          eventOnlyItem: true,
          wowheadId: 251796,
        },
        {
          name: "Reins of the Leystone Basilisk",
          cost: 10000,
          id: 1242,
          eventOnlyItem: true,
          wowheadId: 250424,
        },
        {
          name: "Reins of the Felslate Basilisk",
          cost: 10000,
          id: 1243,
          eventOnlyItem: true,
          wowheadId: 250425,
        },
        {
          name: "Reins of the Slag Basilisk",
          cost: 10000,
          id: 1244,
          eventOnlyItem: true,
          wowheadId: 250423,
        },
        {
          name: "Reins of the Aquamarine Basilisk",
          cost: 10000,
          id: 1245,
          eventOnlyItem: true,
          wowheadId: 250426,
        },
        {
          name: "Reins of the Long-Forgotten Hippogryph",
          cost: 20000,
          id: 1246,
          eventOnlyItem: false,
          wowheadId: 138258,
        },
        {
          name: "Spirit of Eche'ro",
          cost: 40000,
          id: 1247,
          eventOnlyItem: false,
          wowheadId: 131734,
        },
        {
          name: "Fathom Dweller",
          cost: 20000,
          id: 1248,
          eventOnlyItem: false,
          wowheadId: 138201,
        },
        {
          name: "Arcadian War Turtle",
          cost: 100000,
          id: 1249,
          eventOnlyItem: false,
          wowheadId: 141713,
        },
        {
          name: "Reins of the Arcberry Manasaber",
          cost: 10000,
          id: 1250,
          eventOnlyItem: true,
          wowheadId: 250728,
        },
        {
          name: "Reins of the Bonesteed of Triumph",
          cost: 10000,
          id: 1251,
          eventOnlyItem: true,
          wowheadId: 250761,
        },
        {
          name: "Reins of the Bonesteed of Bloodshed",
          cost: 10000,
          id: 1252,
          eventOnlyItem: true,
          wowheadId: 250760,
        },
        {
          name: "Reins of the Bonesteed of Plague",
          cost: 10000,
          id: 1253,
          eventOnlyItem: true,
          wowheadId: 250759,
        },
        {
          name: "Reins of the Bonesteed of Oblivion",
          cost: 10000,
          id: 1254,
          eventOnlyItem: true,
          wowheadId: 250758,
        },
        {
          name: "Midnight's Eternal Reins",
          cost: 100000,
          id: 1255,
          eventOnlyItem: false,
          wowheadId: 142236,
        },
        {
          name: "Living Infernal Core",
          cost: 100000,
          id: 1256,
          eventOnlyItem: false,
          wowheadId: 137574,
        },
        {
          name: "Fiendish Hellfire Core",
          cost: 100000,
          id: 1257,
          eventOnlyItem: false,
          wowheadId: 137575,
        },
        {
          name: "Cloudwing Hippogryph",
          cost: 20000,
          id: 1258,
          eventOnlyItem: false,
          wowheadId: 147806,
        },
        {
          name: "Highmountain Elderhorn",
          cost: 20000,
          id: 1259,
          eventOnlyItem: false,
          wowheadId: 147807,
        },
        {
          name: "Leywoven Flying Carpet",
          cost: 20000,
          id: 1260,
          eventOnlyItem: false,
          wowheadId: 143764,
        },
        {
          name: "Valarjar Stormwing",
          cost: 20000,
          id: 1261,
          eventOnlyItem: false,
          wowheadId: 147805,
        },
        {
          name: "Abyss Worm",
          cost: 100000,
          id: 1262,
          eventOnlyItem: false,
          wowheadId: 143643,
        },
        {
          name: "Wild Dreamrunner",
          cost: 20000,
          id: 1263,
          eventOnlyItem: false,
          wowheadId: 147804,
        },
        {
          name: "Reins of the Ghastly Ur'zul",
          cost: 10000,
          id: 1264,
          eventOnlyItem: true,
          wowheadId: 250192,
        },
        {
          name: "Reins of the Luminous Mana Ray",
          cost: 10000,
          id: 1265,
          eventOnlyItem: true,
          wowheadId: 250748,
        },
        {
          name: "Reins of the Albino Mana Ray",
          cost: 10000,
          id: 1266,
          eventOnlyItem: true,
          wowheadId: 250747,
        },
        {
          name: "Reins of the Bloodtooth Mana Ray",
          cost: 10000,
          id: 1267,
          eventOnlyItem: true,
          wowheadId: 250746,
        },
        {
          name: "Reins of the Fel-Scarred Mana Ray",
          cost: 10000,
          id: 1268,
          eventOnlyItem: true,
          wowheadId: 250745,
        },
        {
          name: "Garnet Ruinstrider",
          cost: 10000,
          id: 1269,
          eventOnlyItem: true,
          wowheadId: 250803,
        },
        {
          name: "Reins of the Longhorned Beryl Talbuk",
          cost: 10000,
          id: 1270,
          eventOnlyItem: true,
          wowheadId: 250806,
        },
        {
          name: "Reins of the Longhorned Argussian Talbuk",
          cost: 10000,
          id: 1271,
          eventOnlyItem: true,
          wowheadId: 250805,
        },
        {
          name: "Longhorned Bleakhoof Talbuk",
          cost: 10000,
          id: 1272,
          eventOnlyItem: true,
          wowheadId: 250804,
        },
        {
          name: "Reins of the Longhorned Sable Talbuk",
          cost: 10000,
          id: 1273,
          eventOnlyItem: true,
          wowheadId: 250802,
        },
        {
          name: "Antoran Charhound",
          cost: 100000,
          id: 1274,
          eventOnlyItem: false,
          wowheadId: 152816,
        },
        {
          name: "Biletooth Gnasher",
          cost: 40000,
          id: 1275,
          eventOnlyItem: false,
          wowheadId: 152903,
        },
        {
          name: "Acid Belcher",
          cost: 40000,
          id: 1276,
          eventOnlyItem: false,
          wowheadId: 152904,
        },
        {
          name: "Crimson Slavermaw",
          cost: 40000,
          id: 1277,
          eventOnlyItem: false,
          wowheadId: 152905,
        },
        {
          name: "Blessed Felcrusher",
          cost: 20000,
          id: 1278,
          eventOnlyItem: false,
          wowheadId: 153043,
        },
        {
          name: "Avenging Felcrusher",
          cost: 20000,
          id: 1279,
          eventOnlyItem: false,
          wowheadId: 153044,
        },
        {
          name: "Glorious Felcrusher",
          cost: 20000,
          id: 1280,
          eventOnlyItem: false,
          wowheadId: 153042,
        },
        {
          name: "Vile Fiend",
          cost: 40000,
          id: 1281,
          eventOnlyItem: false,
          wowheadId: 152790,
        },
        {
          name: "Darkspore Mana Ray",
          cost: 40000,
          id: 1282,
          eventOnlyItem: false,
          wowheadId: 152843,
        },
        {
          name: "Lambent Mana Ray",
          cost: 40000,
          id: 1283,
          eventOnlyItem: false,
          wowheadId: 152844,
        },
        {
          name: "Felglow Mana Ray",
          cost: 40000,
          id: 1284,
          eventOnlyItem: false,
          wowheadId: 152841,
        },
        {
          name: "Scintillating Mana Ray",
          cost: 40000,
          id: 1285,
          eventOnlyItem: false,
          wowheadId: 152840,
        },
        {
          name: "Vibrant Mana Ray",
          cost: 40000,
          id: 1286,
          eventOnlyItem: false,
          wowheadId: 152842,
        },
        {
          name: "Maddened Chaosrunner",
          cost: 40000,
          id: 1287,
          eventOnlyItem: false,
          wowheadId: 152814,
        },
        {
          name: "Shackled Ur'zul",
          cost: 100000,
          id: 1288,
          eventOnlyItem: false,
          wowheadId: 152789,
        },
      ],
    },
    {
      name: "Horos",
      description: "Rare Collections",
      id: 7,
      items: [
        {
          name: "Mini Mana Bomb",
          cost: 500,
          id: 257,
          eventOnlyItem: true,
          wowheadId: 89205,
        },
        {
          name: "Theramore Tabard",
          cost: 500,
          id: 276,
          eventOnlyItem: true,
          wowheadId: 89196,
        },
        {
          name: "Odd Polished Stone",
          cost: 2200,
          id: 236,
          eventOnlyItem: false,
          wowheadId: 104262,
        },
        {
          name: "Battle Horn",
          cost: 3850,
          id: 237,
          eventOnlyItem: false,
          wowheadId: 86565,
        },
        {
          name: "Bottled Tornado",
          cost: 3850,
          id: 238,
          eventOnlyItem: false,
          wowheadId: 134023,
        },
        {
          name: "Chalice of Secrets",
          cost: 3850,
          id: 239,
          eventOnlyItem: false,
          wowheadId: 86575,
        },
        {
          name: "Essence of the Breeze",
          cost: 3850,
          id: 240,
          eventOnlyItem: false,
          wowheadId: 86590,
        },
        {
          name: "Helpful Wikky's Whistle",
          cost: 3850,
          id: 241,
          eventOnlyItem: false,
          wowheadId: 86594,
        },
        {
          name: "Kang's Bindstone",
          cost: 3850,
          id: 242,
          eventOnlyItem: false,
          wowheadId: 86571,
        },
        {
          name: "Ai-Li's Skymirror",
          cost: 4950,
          id: 243,
          eventOnlyItem: false,
          wowheadId: 86589,
        },
        {
          name: "Eternal Warrior's Sigil",
          cost: 4950,
          id: 244,
          eventOnlyItem: false,
          wowheadId: 86578,
        },
        {
          name: "Farwater Conch",
          cost: 4950,
          id: 245,
          eventOnlyItem: false,
          wowheadId: 86581,
        },
        {
          name: "Hozen Beach Ball",
          cost: 4950,
          id: 246,
          eventOnlyItem: false,
          wowheadId: 86593,
        },
        {
          name: "Panflute of Pandaria",
          cost: 4950,
          id: 247,
          eventOnlyItem: false,
          wowheadId: 86586,
        },
        {
          name: "Salyin Battle Banner",
          cost: 4950,
          id: 248,
          eventOnlyItem: false,
          wowheadId: 86583,
        },
        {
          name: "Shard of Archstone",
          cost: 4950,
          id: 249,
          eventOnlyItem: false,
          wowheadId: 86573,
        },
        {
          name: "Aqua Jewel",
          cost: 7700,
          id: 250,
          eventOnlyItem: false,
          wowheadId: 86582,
        },
        {
          name: "Mr. Smite's Brass Compass",
          cost: 7700,
          id: 251,
          eventOnlyItem: false,
          wowheadId: 86568,
        },
        {
          name: "Pandaren Firework Launcher",
          cost: 7700,
          id: 252,
          eventOnlyItem: false,
          wowheadId: 86588,
        },
        {
          name: "Blackflame Daggers",
          cost: 38500,
          id: 253,
          eventOnlyItem: false,
          wowheadId: 104302,
        },
        {
          name: "Warning Sign",
          cost: 38500,
          id: 254,
          eventOnlyItem: false,
          wowheadId: 104331,
        },
        {
          name: "Gastropod Shell",
          cost: 50000,
          id: 255,
          eventOnlyItem: false,
          wowheadId: 98136,
        },
        {
          name: "Eternal Kiln",
          cost: 50000,
          id: 256,
          eventOnlyItem: false,
          wowheadId: 104309,
        },
      ],
    },
  ],
};

export default bronze;
